---
title: "exam20180111"
author: "Shahin Salehi"
date: "8/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r as1}
# with and without scaling the features
#how many components?
# explain why so few can capture so much

set.seed(12345)
data = read.csv("video.csv")
n = dim(data)[1]
id = sample(1:n, floor(0.5 * n))
train = data[id,]
test = data[-id,]

# remove utime dim per instruction
data$utime=c()

# remove codec since its not numeric
data$codec = c()

# PCA WITH SCALING

# apply PCA
pcares = prcomp(data)
# lambda vals
lambda = pcares$sdev^2
# eigenvals 
lambda
# variation
sprintf("%2.3f", lambda/sum(lambda) * 100)
#built in function that displays PCA variation
screeplot(pcares)

#variation
pca_scale = prcomp(scale(data))
s_lambda = pca_scale$sdev^2


sprintf("%2.3f", cumsum(lambda)/sum(lambda) * 100)

sprintf("%2.3f", cumsum(s_lambda)/sum(s_lambda) * 100)

#for case 1 
arr =  cumsum(lambda)/sum(lambda) * 100
min(which(arr >= 95))

#for case 2
arr = cumsum(s_lambda)/ sum(s_lambda) * 100
min(which(arr >= 95))

##### 
# 3 use pcr model with M = 8 ?



```
